### ISSUE TITLE
请问OCR的精度计算是以什么标准呢？

### ISSUE THREAD

**Issue by tink2123** [SCUT-DLVCLab/GPT-4V_OCR#17]
非常感谢您公开的优秀工作，有一个问题想请教一下，在计算各个OCR指标时是以什么标准呢？编辑距离？character-level 还是word-level？

我个人直接测试GPT4-V的时候，使用您提供的prompt，总是难以得到准确结果，导致计算出的准确率非常低。例如：

prompt：`What are all the scene text in the image? Do not translate.`
answer: 
```
The scene text in the image includes the following:
Chinese characters at the top part of the emblem.
“JUMBO FLOATING RESTAURANT” written in English in the middle part of the emblem.
“HONG KONG” written in English at the bottom part of the emblem.
A red stamp at the bottom right corner with the word “AWESOME!” in English.
```

请问作者团队是如何处理结果的呢？期待您的回复。

**Comment by shi-yx** [comment]
您好，对于这个问题，我们在arXiv版本中是直接人工提取回答的中的答案，如JUMBO FLOATING RESTAURANT、HONG KONG、AWESOME。这是因为当时OpenAI未开放API，网页端次数非常有限，所以数据量不大可以这么操作。

数据量较大时肯定不能再这么操作了，目前我们使用类似的prompt：What are all the scene text in the image? Return results directly as a list, e.g. [``text1", ``text2", ...].

这样得到的结果可以用简单的代码编写规则提取回答。

**Comment by shi-yx** [comment]
您好，对于这个问题，我们在arXiv版本中是直接人工提取回答的中的答案，如JUMBO FLOATING RESTAURANT、HONG KONG、AWESOME。因为当时OpenAI未开放API，网页端次数非常有限，所以数据量不大，可以这么操作。

数据量较大时肯定不能再这么操作了，所以目前我们使用类似的prompt：What are all the scene text in the image? Return results directly as a list, e.g. ["text1", "text2", ...].

这样得到的结果可以用简单的代码编写规则提取回答。
