### ISSUE TITLE
GPT4V调用OCR的API了吗

### ISSUE THREAD

**Issue by iamhankai** [SCUT-DLVCLab/GPT-4V_OCR#8]
根据你们的评测和观察，你们觉得，GPT4V调用已有OCR模型了吗，用OCR模型识别的文本输入到GPT4V？

**Comment by KainingYing** [comment]
同问，但是我也感觉有调用OCR的专家模型

**Comment by shannanyinxiang** [comment]
根据我们的初步实验和分析，GPT-4V大概率没有使用OCR专家模型，其原因一是GPT-4V在针对OCR任务的回答中仍然会出现幻觉，特别是中文场景；二是GPT-4V文本检测的能力很差。

**Comment by iamhankai** [comment]
谢谢，GPT-4V文本检测的能力很差这个在论文里没看到评测

**Comment by shannanyinxiang** [comment]
文本检测部分在后续版本中可能会加入，感谢您的关注
